- name: app-setup 
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: java
  ansible.builtin.import_role:
    name: common
    tasks_from: java

- name: mysql_setup 
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql_setup

- name: systemd 
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd





