- name: create roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Recursively remove existing directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create /app dir
  ansible.builtin.file:
    path: /app
    state: directory

- name: "download {{component}} application code"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: "extract the {{component}} application"
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes